package Tech.CodingClub.utility;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.Scanner;

public class FileUtility {
    public static boolean createFile(String fileNameWithPath){
        File file = new File(fileNameWithPath);
        boolean fileCreated = false;
        try {
            fileCreated = file.createNewFile();
            file.createNewFile();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        return fileCreated;
    }

    public static ArrayList<String> readFileAsList(String fileName) {
        Scanner scanner = null;
        ArrayList<String> strings = new ArrayList<String>();
        try {
            File file = new File(fileName);
            scanner = new Scanner(file);
            while (scanner.hasNext()) {
                String line = scanner.nextLine();
                strings.add(line);
            }

        }catch (Exception e) {
            e.printStackTrace();

        }finally {
            if (scanner != null) {
                //This is very important
                scanner.close();
            }
        }
        return strings;
    }

    public static boolean writeToFile(String fileNameWithPath, String content) {

        try {
            FileWriter fileWriter = new FileWriter(fileNameWithPath);

            fileWriter.append(content);
            fileWriter.close();

        } catch (Exception e) {
        }
        return true;
    }
    public static boolean appendToFile(String fileName, String content) {
        try {
            FileWriter fileWriter = new FileWriter(fileName, true);

            fileWriter.append("\n");
            fileWriter.append(content);
            fileWriter.close();
        } catch (Exception e) {
            return false;


        }
        return true;
    }

    public static void main(String[] args) {

        System.out.println("This side is Santosh Kale");
        System.out.println("Running FileUtility at "+new Date().toString());


        String nameOfNewFile="C:\\Users\\Santosh\\IdeaProjects\\Java\\src\\data\\practice\\file"+"create-file.txt";
        Boolean created = createFile(nameOfNewFile);
        System.out.println("File Created" + created);


        ArrayList<String> stringArrayList =readFileAsList(nameOfNewFile);
        for (String row : stringArrayList) {
            System.out.println("Line : " + row);
        }
        System.out.println("NO of lines in file "+stringArrayList.size());


        String nameOfWriteFile="C:\\Users\\Santosh\\IdeaProjects\\Java\\src\\data\\practice\\file"+"Write-file.txt";

        boolean wroteToFile = writeToFile(nameOfWriteFile, "This File is generated by Santosh Kale System Automatically");
        System.out.println(wroteToFile);
        for (int i=1 ;i<=100;i++){
            String data = i+"";//String
            appendToFile(nameOfWriteFile, data);

        }
        System.out.println("Appended file Length: "+readFileAsList(nameOfWriteFile).size());
    }

}
